### PR TITLE
Updated for Minecraft 1.18.2

### PR DESCRIPTION
**Pull request by gniftygnome**
Besides the 1.18.2 update, this also does a few minor changes:
* Passed the World's instance of Random around for consistency.
* Prevented the mod from removing items from Creative players.

### CODE REVIEW

**Comment by gniftygnome** [comment]
If you aren't interested in maintaining SimpleTech anymore or if you would like a co-maintainer, I'd be interested.  I like the clean implementation and lack of a bunch of unrelated kitchen-sink features.

**Comment by johannesmateboer** [comment]
> If you aren't interested in maintaining SimpleTech anymore or if you would like a co-maintainer, I'd be interested. I like the clean implementation and lack of a bunch of unrelated kitchen-sink features.

Hey! If you want to, you may!

**Comment by gniftygnome** [comment]
> Hey! If you want to, you may!

Heh.  Seems at the moment you have more time than I do now...  I'm happy to see this mod getting worked on though.

**Comment by johannesmateboer** [comment]
I have some time. If you have any suggestions: let me know.

**Pull request merged**
